<div>
	<table class="table table-bordered table-striped table-responsive table-condensed table-hover table-striped">
		<tr>
			<th>订单号</th>
			<td>1234456</td>
			<th>订单价格</th>
			<td>200</td>
			<th>订单时间</th>
			<td>2016-07-17 09:23:10</td>
			<th>订单状态</th>
			<td>待发货</td>
		</tr>
		<tr>
		  	<th>收货人姓名</th>
			<td>张珊</td>
			<th>联系电话</th>
			<td>13568952709</td>
			<th>地址</th>
			<td colspan="3">四川省成都市高新区天府软件园A3</td>
		</tr>
	</table>
	<hr/>
	<table class="table table-striped  table-borderedtable-responsive table-condensed table-hover table-striped">
       <thead>
       		<tr>
       			<th>商品图片</th>
       			<th>商品名称</th>
       			<th>数量</th>
       			<th>价格</th>
       			<th>状态</th>
       		</tr>
       </thead>
       <tbody>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       		<tr>
       			<td></td>
       			<td>羽毛球拍</td>
       			<td>2</td>
       			<td>200</td>
       			<td>已发货</td>
       		</tr>
       </tbody>         		
</table>
</div>
