<div class="easyui-tabs" >   
    <div title="订单信息">   
    	<p style="margin:10px">
    		<a class="btn btn-default" href="#" role="button">确认</a>
			<!--
			<a class="btn btn-primary" href="#" role="button">发货</a>
			<a class="btn btn-success" href="#" role="button">完成</a>
			<a class="btn btn-info" href="#" role="button">退款</a>
			<a class="btn btn-warning" href="#" role="button">退货</a>
			<a class="btn btn-danger" href="#" role="button">取消</a>
			-->
    	</p>
       	<table class="table table-striped table-bordered table-hover table-condensed">
 			<tr>
 				<th>订单号</th>
 				<td>20080802</td>
 				<th>创建日期</th>
 				<td>2016-08-02</td>
 			</tr>
 			<tr>
 				<th>订单状态</th>
 				<td>已确认</td>
 				<th>支付状态</th>
 				<td>已付款</td>
 			</tr>
 			<tr>
 				<th>配送状态</th>
 				<td>发货中</td>
 				<th>用户名</th>
 				<td>tom@163.com</td>
 			</tr>
 			<tr>
 				<th>订单金额</th>
 				<td>200</td>
 				<th>已付款</th>
 				<td>200</td>
 			</tr>
 			<tr>
 				<th>商品重量</th>
 				<td>20</td>
 				<th>商品数量</th>
 				<td>2</td>
 			</tr>
 			<tr>
 				<th>运费</th>
 				<td>10元</td>
 				<th>支付方式</th>
 				<td>微信</td>
 			</tr>
 			<tr>
 				<th>收货人</th>
 				<td>张珊</td>
 				<th>电话</th>
 				<td>13568952709</td>
 			</tr>
 			<tr>
 				<th>地区</th>
 				<td>成都市高新区</td>
 				<th>地址</th>
 				<td>天府软件园A3</td>
 			</tr>
 			<tr>
 				<th>附言</th>
 				<td colspan="3">20080802</td>
 			</tr>
 		</table> 
    </div>   
    <div title="商品信息">   
 		<table class="table table-striped  table-borderedtable-responsive table-condensed table-hover table-striped">
		       <thead>
		       		<tr>
		       			<th>编号</th>
		       			<th>商品名称</th>
		       			<th>数量</th>
		       			<th>价格</th>
		       			<th>小计</th>
		       			<th>状态</th>
		       		</tr>
		       </thead>
		       <tbody>
		       		<tr>
		       			<td>201608023214</td>
		       			<td>羽毛球拍</td>
		       			<td>2</td>
		       			<td>200</td>
		       			<td>400</td>
		       			<td>已发货</td>
		       		</tr>
		       		<tr>
		       			<td>201608023214</td>
		       			<td>羽毛球拍</td>
		       			<td>2</td>
		       			<td>200</td>
		       			<td>400</td>
		       			<td>已发货</td>
		       		</tr>
		       		<tr>
		       			<td>201608023214</td>
		       			<td>羽毛球拍</td>
		       			<td>2</td>
		       			<td>200</td>
		       			<td>400</td>
		       			<td>已发货</td>
		       		</tr>
		       		<tr>
		       			<td>201608023214</td>
		       			<td>羽毛球拍</td>
		       			<td>2</td>
		       			<td>200</td>
		       			<td>400</td>
		       			<td>已发货</td>
		       		</tr>
		       		<tr>
		       			<td>201608023214</td>
		       			<td>羽毛球拍</td>
		       			<td>2</td>
		       			<td>200</td>
		       			<td>400</td>
		       			<td>已发货</td>
		       		</tr>
		       		<tr>
		       			<td>201608023214</td>
		       			<td>羽毛球拍</td>
		       			<td>2</td>
		       			<td>200</td>
		       			<td>400</td>
		       			<td>已发货</td>
		       		</tr>
		       </tbody>         		
		</table>
    </div>   
    <div title="收款信息" >   
       	<table class="table table-striped  table-borderedtable-responsive table-condensed table-hover table-striped">
		       <thead>
		       		<tr>
		       			<th>编号</th>
		       			<th>方式</th>
		       			<th>支付方式</th>
		       			<th>付款金额</th>
		       			<th>付款日期</th>
		       			<th>状态</th>
		       		</tr>
		       </thead>
		       <tbody>
		       		<tr>
		       			<td>201608023214</td>
		       			<td>羽毛球拍</td>
		       			<td>微信</td>
		       			<td>200</td>
		       			<td>2016-08-02</td>
		       			<td>已收款</td>
		       		</tr>
		       </tbody>         		
		</table>
    </div>   
    <div title="发货信息" >   
        	<table class="table table-striped  table-borderedtable-responsive table-condensed table-hover table-striped">
		       <thead>
		       		<tr>
		       			<th>编号</th>
		       			<th>配送方式</th>
		       			<th>物流公司</th>
		       			<th>运单号</th>
		       			<th>收货人</th>
		       			<th>创建日期</th>
		       		</tr>
		       </thead>
		       <tbody>
		       		<tr>
		       			<td>201608023214</td>
		       			<td>羽毛球拍</td>
		       			<td>微信</td>
		       			<td>200</td>
		       			<td>2016-08-02</td>
		       			<td>已收款</td>
		       		</tr>
		       </tbody>         		
		</table>
    </div>   
    <div title="退款信息" >   
     	  <table class="table table-striped  table-borderedtable-responsive table-condensed table-hover table-striped">
		       <thead>
		       		<tr>
		       			<th>编号</th>
		       			<th>方式</th>
		       			<th>退款方式</th>
		       			<th>退款金额</th>
		       			<th>退款日期</th>
		       			<th>状态</th>
		       		</tr>
		       </thead>
		       <tbody>
		       		<tr>
		       			<td>201608023214</td>
		       			<td>羽毛球拍</td>
		       			<td>微信</td>
		       			<td>200</td>
		       			<td>2016-08-02</td>
		       			<td>已退款</td>
		       		</tr>
		       </tbody>         		
		</table>
    </div>   
    <div title="退货信息" >   
        	<table class="table table-striped  table-borderedtable-responsive table-condensed table-hover table-striped">
		       <thead>
		       		<tr>
		       			<th>编号</th>
		       			<th>配送方式</th>
		       			<th>物流公司</th>
		       			<th>运单号</th>
		       			<th>收货人</th>
		       			<th>创建日期</th>
		       		</tr>
		       </thead>
		       <tbody>
		       		<tr>
		       			<td>201608023214</td>
		       			<td>羽毛球拍</td>
		       			<td>微信</td>
		       			<td>200</td>
		       			<td>2016-08-02</td>
		       			<td>已收款</td>
		       		</tr>
		       </tbody>         		
		</table>
    </div>   
    <div title="订单日志" >   
        	<table class="table table-striped  table-borderedtable-responsive table-condensed table-hover table-striped">
		       <thead>
		       		<tr>
		       			<th>类型</th>
		       			<th>操作员</th>
		       			<th>操作内容</th>
		       			<th>日期</th>
		       		</tr>
		       </thead>
		       <tbody>
		       		<tr>
		       			<td>发货</td>
		       			<td>admin</td>
		       			<td>已通知快递员收货</td>
		       			<td>2016-08-02</td>
		       		</tr>
		       </tbody>         		
		</table>
    </div>  
</div>  